tools:
    php_code_sniffer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true
    php_cs_fixer: true
    php_analyzer:
        config:
            doc_comment_fixes:
                enabled: true
    php_changetracking: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 600
