language: php

sudo: false

addons:
  apt:
    packages:
    - graphviz

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"

matrix:
  allow_failures:
    - php: "7.1"

services:
  - memcached
  - redis-server

notifications:
  email: false

env:
  global:
    - CC_TEST_REPORTER_ID=44bde58b55e4b1b6e54683a0a66a21c693118fde0a2111d51037b11be91f5673
    - TWFY_TEST_DB_HOST="127.0.0.1" TWFY_TEST_DB_USER="root" TWFY_TEST_DB_PASS="" TWFY_TEST_DB_NAME="twfy_test"
    - secure: MhpIz8iPjYyVYzAZKzXVD1gJ44XwkM5q/ysr92e827c2VoDmDeZy4TgKA7HuKsw02ou4AwsR4mQFWhKxd21SruhAZhOQBMCqP3+5UwnXISf8vqowfFH9Ml9iLzeWI2Sdz8c0nEO4rs9ObMZa2VWzrJyd49ZPt7zex1x1JYJ8OeM=

before_script:
 - mysql -e "create database IF NOT EXISTS twfy_test;" -uroot
 - mysql -u root twfy_test < db/schema.sql
 - php composer.phar install --no-interaction --prefer-source
 - bash -c 'if [ $(echo "$TRAVIS_PHP_VERSION>=7.0" | bc -l) == 1 ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; else echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --exclude-group xapian

after_script:
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
 - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.4" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'
 - bash -c '[ "$TRAVIS_PHP_VERSION-$TRAVIS_BRANCH-$TRAVIS_PULL_REQUEST" = "5.4-master-false" ] && bash build-docs.sh'
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
